ci: ajust test CI (#8)
* ci: ajust test CI

* chore: Update CI configuration

* chore: Update actions/checkout version

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -1,10 +1,10 @@
 name: CI
 
 on:
-  pull_request_target:
+  pull_request:
     branches:
+    - v*
     - main
-    - beta
     types:
     - synchronize
     - edited
@@ -32,7 +32,7 @@ jobs:
       GITHUB_TOKEN: ${{ github.token }}
     steps:
     - name: Checkout
-      uses: actions/checkout@v3
+      uses: actions/checkout@v4
 
     - name: Setup Node
       uses: actions/setup-node@v3
@@ -52,7 +52,31 @@ jobs:
     - name: Run Build
       run: npm run build
 
-    - name: Run Health Check
-      uses: ./action.yml
+  # test action works running from the graph
+  test-action:
+    needs: semantic_pr
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        # We must fetch at least the immediate parents so that if this is
+        # a pull request then we can checkout the head.
+        fetch-depth: 2
+
+    - name: Test action
+      uses: ./
       with:
         file: "./test.txt"
+      env:
+        NAME: "Eduardo"
+
+    - name: Asset file contents
+      run: cat ./test.txt
+
+    # trigger action failure if content of test.txt is not "test"
+    - name: Check file contents
+      run: |
+        if [ "$(cat ./test.txt)" != "Hello, Eduardo" ]; then
+          echo "File contents are not as expected"
+          exit 1
+        fi
